version: 2.1
jobs:
  lint-scripts:
    docker:
      - image: koalaman/shellcheck-alpine
    steps:
      - checkout
      - run:
          name: lint-scripts
          command: .circleci/lint-scripts.sh

  install-mysql-minimal:
    docker:
      - image: circleci/ruby:2.4.4
      - image: circleci/mysql:5.7-ram
        command: --max_allowed_packet=64MB
        environment:
          MYSQL_DATABASE: zammad_test
          MYSQL_USER: zammad_test
          MYSQL_PASSWORD: zammad_test
    environment:
      RAILS_ENV: test
    steps:
      - checkout
      - run:
          name: install-mysql-minimal
          command: .circleci/install-minimal.sh

workflows:
  version: 2
  install_unittest_dockerbuild:
    jobs:
      - lint-scripts
      - install-mysql-minimal:
          requires:
            - lint-scripts
